name: Test CityHeaven

on:
 workflow_dispatch:

jobs:
 test:
  runs-on: windows-latest


  steps:
  - name: Test API
    shell: powershell
    run: |
      Write-Host "開始測試"

      $url = "https://www.cityheaven.net/api/okinawa/v1/shops/diaries/shopid-2000001072/type0/girlid-24886544/sort0/"

      try {
          $json = Invoke-RestMethod $url

          Write-Host "成功"

          Write-Host "最新ID:"
          Write-Host $json.diary_id[0]
      }
      catch {
          Write-Host "失敗"
          Write-Host $_
      }

